name: List Synonymy

on:
  push:
    branches:
      - dev-synonymy

jobs:
  generate-response:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Restore cached Node dependencies
        id: restore-cached-node-dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: node-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install Node dependencies
        if: steps.restore-cached-node-dependencies.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache Node dependencies
        id: cache-node-dependencies
        uses: actions/cache/save@v5
        if: steps.restore-cached-node-dependencies.outputs.cache-hit != 'true'
        with:
          path: |
            ./node_modules
            package-lock.json
          key: ${{ steps.restore-cached-node-dependencies.outputs.cache-primary-key }}

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull Gemma 4 E4B Model
        run: ollama pull gemma4:e4b
      
      - name: Unzip tags
        run: unzip tags.zip
      
      - name: Unzip synonymies
        run: unzip synonymies.zip

      - name: Generate prompts
        run: |
          node generate-prompts.js
      
      - name: List synonymies
        run: |
          chmod +x ./synonymy.sh
          ./synonymy.sh
      
      - name: Merge synonymies
        run: zip -ru synonymies.zip ./synonymies
      
      - name: Separate changed files
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: |
          mkdir -p "./deploy"
          cp -f "synonymies.zip" "./deploy/synonymies.zip"

      - name: Deploy with gh-pages
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -a -d deploy -u "github-actions-bot <support+actions@github.com>" -b dev-synonymy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
