name: Update
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  workflow_dispatch:

jobs: 
  update: # The name of the job
    runs-on: ubuntu-latest # The type of runner to use
    steps: 
      - name: Check out repository code # The name of the step
        uses: actions/checkout@v4 # The action to use

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # The version of Node.js to use

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Node dependencies
        run: npm install

      - name: Install Python dependencies
        run: pip install openai-clip torch torchvision pillow

      - name: Fetch versions.json
        run: curl "https://raw.githubusercontent.com/marella/material-symbols/refs/heads/main/metadata/versions.json" -o "./tmp/versions.json"
      
      - name: Download updated symbols
        run: node download-updated-symbols.js
      
      - name: Rasterize
        run: node rasterize.js
      
      - name: Add tags
        run: python tag.py
      
      - name: Remove deleted symbols
        run: node remove-deleted-symbols.js
      
      - name: Update versions.json
        run: cp -f "./tmp/versions.json" "versions.json"
      
      - name: Remove temporary files
        run: rm -rf "./tmp"
      
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -u "github-actions-bot <support+actions@github.com>" -b process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}