name: Update
on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Node dependencies
        run: npm install

      - name: Install Python dependencies
        run: pip install openai-clip torch torchvision pillow

      - name: Create temporary directory
        run: mkdir ./tmp

      - name: Fetch versions.json
        run: curl "https://raw.githubusercontent.com/marella/material-symbols/refs/heads/main/metadata/versions.json" -o "./tmp/versions.json"
      
      - name: Download updated symbols
        run: node download-updated-symbols.js
      
      - name: Rasterize
        run: node rasterize.js
      
      - name: Add tags
        run: python tag.py

      - name: Merge tags
        run: zip -ru tags.zip ./tags # -x "*.DS_Store"
      
      - name: Separate changed files
        run: |
          mkdir -p "./deploy"
          cp -f "tags.zip" "./deploy/tags.zip"
          cp -f "./tmp/versions.json" "./deploy/versions.json"

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -a -d deploy -u "github-actions-bot <support+actions@github.com>" -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
