name: Update
on:
  schedule:
    - cron: '0 0 * * 1'
    - cron: '0 0 * * 5' # Runs every Monday and Friday at midnight
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-latest
    environment: update
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Restore cached Node dependencies
        id: restore-cached-node-dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            ./node_modules
            package-lock.json
          key: node-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install Node dependencies
        if: steps.restore-cached-node-dependencies.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache Node dependencies
        id: cache-node-dependencies
        uses: actions/cache/save@v5
        if: steps.restore-cached-node-dependencies.outputs.cache-hit != 'true'
        with:
          path: |
            ./node_modules
            package-lock.json
          key: ${{ steps.restore-cached-node-dependencies.outputs.cache-primary-key }}

      - name: Get pip cache directory
        id: get-pip-cache-directory
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Restore cached Python dependencies
        id: restore-cached-python-dependencies
        uses: actions/cache/restore@v5
        with:
          path: ${{ steps.get-pip-cache-directory.outputs.dir }}
          key: python-dependencies-${{ runner.os }}-v1
          restore-keys: |
            python-dependencies-${{ runner.os }}-

      - name: Install Python dependencies
        run: pip install openai-clip torch torchvision pillow
      
      - name: Cache Python dependencies
        id: cache-python-dependencies
        uses: actions/cache/save@v5
        if: steps.restore-cached-python-dependencies.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.get-pip-cache-directory.outputs.dir }}
          key: ${{ steps.restore-cached-python-dependencies.outputs.cache-primary-key }}

      - name: Create temporary directory
        run: mkdir ./tmp

      - name: Fetch versions.json
        run: curl "https://raw.githubusercontent.com/marella/material-symbols/refs/heads/main/metadata/versions.json" -o "./tmp/versions.json"
      
      - name: Download updated symbols
        id: download-updated-symbols
        run: node download-updated-symbols.js

      - name: Rasterize
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: node rasterize.js

      - name: Restore cached CLIP model
        id: restore-cached-clip-model
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cache/clip
          key: clip-model-${{ runner.os }}
          restore-keys: |
            clip-model-${{ runner.os }}

      - name: Add tags
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: python tag.py
      
      - name: Cache CLIP model
        id: cache-clip-model
        uses: actions/cache/save@v5
        if: steps.restore-cached-clip-model.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cache/clip
          key: ${{ steps.restore-cached-clip-model.outputs.cache-primary-key }}

      - name: Merge tags
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: zip -ru tags.zip ./tags # -x "*.DS_Store"

      - name: Separate changed files
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: |
          mkdir -p "./deploy"
          cp -f "tags.zip" "./deploy/tags.zip"
          cp -f "./tmp/versions.json" "./deploy/versions.json"

      - name: Deploy with gh-pages
        if: steps.download-updated-symbols.outputs.updated-symbols-count > 0
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -a -d deploy -u "github-actions-bot <support+actions@github.com>" -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
